'use strict';
const $ = (selector) => document.querySelector(selector);
const worlds = [
  { name: '萌芽小岛', emoji: '🌱', pool: ['a','s','d','f','j','k','l','g','h','q','w','e','r','t','y','u','i','o','p','z','x','c','v','b','n','m'], filter: 'none', reward: '「初次见面」伙伴贴纸' },
  { name: '蘑菇森林', emoji: '🍄', pool: ['cat','sun','dog','bee','egg','pig','red','sky','fox','owl','jam','leaf'], filter: 'hue-rotate(24deg) saturate(.92)', reward: '「森林来信」伙伴贴纸' },
  { name: '星光宇宙', emoji: '🪐', pool: ['s','star','m','moon','u','sun','sky','a','nova','b','orbit','c'], filter: 'hue-rotate(120deg) saturate(.8)', reward: '「星际漫游」伙伴贴纸' }
];
const stickers = [{emoji:'🌱',name:'初次见面'},{emoji:'🍄',name:'森林来信'},{emoji:'🪐',name:'星际漫游'},{emoji:'🌈',name:'彩虹朋友'},{emoji:'🦋',name:'蝴蝶来客'},{emoji:'👑',name:'奇遇小队长'}];
let saved = {stars:0,stickers:[],rounds:0};
try { const data = JSON.parse(localStorage.getItem('gulu-island-v1')); if(data && Number.isFinite(data.stars) && Array.isArray(data.stickers)) saved = {stars: Math.max(0,data.stars),stickers:data.stickers.filter(x => Number.isInteger(x)&&x>=0&&x<6),rounds:Number.isFinite(data.rounds)?Math.max(0,data.rounds):0}; } catch {}
const state = { world:0, mode:'relax', status:'ready', hits:0, combo:0, best:0, target:'', typed:0, seconds:60, clock:null, feedbackTimer:null, nextTimer:null, audio:null, sound:false, lastTarget:'', session:0, dialogResume:false };
const keyboard = $('#keyboard');
for (const row of ['QWERTYUIOP','ASDFGHJKL','ZXCVBNM']) { const el=document.createElement('div');el.className='key-row';for(const letter of row){const key=document.createElement('button');key.type='button';key.className='key'+('ASDFJKL'.includes(letter)?' home':'');key.dataset.key=letter.toLowerCase();key.textContent=letter;key.setAttribute('aria-label','字母 '+letter);key.addEventListener('click',()=>type(letter.toLowerCase()));el.append(key);}keyboard.append(el); }
function persist(){try{localStorage.setItem('gulu-island-v1',JSON.stringify(saved));}catch{}}
function sound(success=true){if(!state.sound)return;try{state.audio??=new(window.AudioContext||window.webkitAudioContext)();state.audio.resume();const now=state.audio.currentTime;const oscillator=state.audio.createOscillator();const gain=state.audio.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(success?523.25:280,now);oscillator.frequency.exponentialRampToValueAtTime(success?783.99:330,now+.12);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.08,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.22);oscillator.connect(gain);gain.connect(state.audio.destination);oscillator.start(now);oscillator.stop(now+.24);}catch{state.sound=false;updateSound();}}
function updateSound(){$('#soundButton').setAttribute('aria-pressed',String(state.sound));$('#soundButton').setAttribute('aria-label',state.sound?'关闭音效':'开启音效');$('.sound-off').hidden=state.sound;}
function update(){ $('#totalStars').textContent=saved.stars;$('#collectionCount').textContent=saved.stickers.length;$('#missionCounter').innerHTML=state.hits+' <span>/ 8</span>';$('#progressLabel').textContent='✦ '+state.hits+' / 8';$('#missionFill').style.width=state.hits/8*100+'%';$('#missionProgress').setAttribute('aria-valuenow',state.hits);$('#timer').hidden=state.mode!=='challenge';$('#timer').textContent=state.seconds+' 秒';$('#comboLabel').textContent=state.combo>=3?'ϟ '+state.combo+' 连击':'';$('#pauseButton').disabled=!['playing','paused'].includes(state.status);$('#roundLabel').textContent='第 '+(saved.rounds+1)+' 次奇遇';document.querySelectorAll('.key').forEach(key=>{key.classList.toggle('hint',state.status==='playing'&&key.dataset.key===state.target[state.typed]);}); }
function feedback(text){clearTimeout(state.feedbackTimer);$('#feedback').textContent=text;$('#feedback').classList.add('visible');state.feedbackTimer=setTimeout(()=>$('#feedback').classList.remove('visible'),1500);}
function burst(big=false){const box=$('#particles');for(let i=0;i<(big?32:12);i++){const p=document.createElement('span');p.className='particle';p.textContent=['✦','✧','●'][i%3];p.style.setProperty('--x',big?(15+Math.random()*70)+'%':'50%');p.style.setProperty('--y',big?'20%':'40%');p.style.setProperty('--dx',(-130+Math.random()*260)+'px');p.style.setProperty('--dy',(-60+Math.random()*220)+'px');p.style.setProperty('--color',['#fff6a2','#fff','#d4ea88','#efb87c'][i%4]);box.append(p);setTimeout(()=>p.remove(),1000);}}
function nextTarget(){if(state.status!=='playing')return;let pool=worlds[state.world].pool;let target=state.hits===0?(state.world===0?'a':state.world===1?'cat':'s'):pool[Math.floor(Math.random()*pool.length)];if(target===state.lastTarget)target=pool[(pool.indexOf(target)+1)%pool.length];state.target=target;state.lastTarget=target;state.typed=0;drawTarget();update();}
function drawTarget(){const field=$('#bubbleField');field.replaceChildren();if(!state.target)return;const b=document.createElement('div');b.className='target-bubble'+(state.target.length>1?' word':'');b.setAttribute('aria-label','请敲 '+state.target.toUpperCase());for(let i=0;i<state.target.length;i++){const s=document.createElement('span');s.textContent=state.target[i].toUpperCase();s.className=i<state.typed?'typed-char':'';b.append(s);}field.append(b);$('#keyboardHint').textContent=state.target.length>1?'依次敲出字母，就能收集这颗星星':'找到发光的 '+state.target[state.typed]?.toUpperCase()+' 键';}
function start(){clearInterval(state.clock);clearTimeout(state.nextTimer);state.session++;state.status='playing';state.hits=0;state.combo=0;state.best=0;state.seconds=60;state.lastTarget='';$('#welcome').classList.add('is-hidden');$('#feedback').classList.remove('visible');$('#companionSpeech').textContent='出发！第一颗星星就在前面！';$('#stageTip').textContent=state.mode==='relax'?'没有倒计时，按你的节奏来':'收集星星，看看 60 秒内的小进步';nextTarget();if(state.mode==='challenge')state.clock=setInterval(()=>{if(state.status!=='playing')return;state.seconds--;update();if(state.seconds<=0)finish(false);},1000);sound();}
function type(letter){if(state.status!=='playing'||!state.target)return;const key=$('[data-key="'+letter+'"]');if(key){key.classList.add('pressed');setTimeout(()=>key.classList.remove('pressed'),160);}if(letter!==state.target[state.typed]){state.combo=0;feedback('没关系，再找找发光的按键 ✧');const b=$('.target-bubble');if(b){b.classList.remove('wiggle');void b.offsetWidth;b.classList.add('wiggle');}sound(false);update();return;}sound();state.typed++;if(state.typed<state.target.length){drawTarget();update();return;}state.hits++;state.combo++;state.best=Math.max(state.best,state.combo);saved.stars++;persist();$('.target-bubble')?.classList.add('pop');state.target='';burst(state.combo>0&&state.combo%3===0);const phrases=['找到了！星星亮起来啦 ✦','好棒！再往前走一点！','你的手指会变魔法耶！','咕噜为你转了个圈！'];feedback(state.combo>=3?'哇，'+state.combo+' 连击！魔法满满 ✨':phrases[(state.hits-1)%phrases.length]);$('#companionSpeech').textContent=state.hits>=6?'快到家啦！你真是超棒的搭子！':'又一颗星星！谢谢你陪我冒险。';update();const session=state.session;state.nextTimer=setTimeout(()=>{if(session!==state.session)return;if(state.hits>=8){if(state.status==='playing')finish(true);}else nextTarget();},450);}
function finish(completed){clearInterval(state.clock);clearTimeout(state.nextTimer);state.status='finished';state.target='';$('#bubbleField').replaceChildren();update();let reward='';if(completed){saved.rounds++;let id=state.world;if(saved.stickers.includes(id))id=[3,4,5].find(n=>!saved.stickers.includes(n))??-1;if(id>=0){saved.stickers.push(id);reward='<p>新朋友加入！获得「'+stickers[id].name+'」贴纸。</p>';}else reward='<p>所有伙伴都到齐了！星星还在继续闪耀。</p>';persist();burst(true);update();}$('#companionSpeech').textContent=completed?'我们到家啦！和你一起真开心。':'每一颗星星都算数，下次再一起玩！';showDialog('<div class="dialog-icon">'+(completed?'🎉':'🌟')+'</div><h2>'+(completed?'耶！把星星带回家啦':'收获了一口袋小进步！')+'</h2>'+(completed?reward:'<p>时间到！你找到的 '+state.hits+' 颗星星都留下啦。</p>')+'<div class="result-stats"><div><strong>'+state.hits+'</strong><span>收获星星</span></div><div><strong>'+state.best+'</strong><span>最高连击</span></div></div><button class="primary-button" id="againButton">再来一次奇遇 →</button><button class="secondary-button" id="rewardCollection">看看我的收藏</button>',false);$('#againButton').onclick=()=>{closeDialog(false);start();};$('#rewardCollection').onclick=showCollection;}
function pause(){if(state.status!=='playing')return;state.status='paused';update();showDialog('<div class="dialog-icon">☁️</div><h2>咕噜陪你歇一会儿</h2><p>星星会乖乖等着。<br>准备好以后，再一起出发。</p><button class="primary-button" id="resumeButton">继续冒险 →</button><button class="secondary-button" id="restartButton">从头再玩一次</button>',true);$('#resumeButton').onclick=()=>closeDialog(true);$('#restartButton').onclick=()=>{closeDialog(false);start();};}
function showDialog(html,resume=state.status==='playing'){if(state.status==='playing')state.status='paused';state.dialogResume=resume;$('#dialogContent').innerHTML=html;if(!$('#gameDialog').open)$('#gameDialog').showModal();update();}
function closeDialog(resume=true){$('#gameDialog').close();if(resume&&state.dialogResume){state.status='playing';if(state.hits>=8){state.dialogResume=false;finish(true);return;}if(!state.target)nextTarget();}state.dialogResume=false;if(resume&&state.status==='finished')resetReady();update();}
function showCollection(){const resume=state.status==='playing'||(state.status==='paused'&&state.dialogResume);showDialog('<div class="dialog-icon">🎒</div><h2>我的伙伴收藏</h2><p>每完成一次奇遇，就有新朋友来敲门。<br>已认识 '+saved.stickers.length+' / 6 位伙伴 · 星星累计 '+saved.stars+' 颗</p><div class="sticker-grid">'+stickers.map((s,i)=>'<div class="sticker '+(saved.stickers.includes(i)?'':'locked')+'"><span>'+s.emoji+'</span><small>'+(saved.stickers.includes(i)?s.name:'等待相遇')+'</small></div>').join('')+'</div><p style="font-size:12px">收藏保存在这台设备的浏览器里</p>',resume);}
function showHelp(){const resume=state.status==='playing'||(state.status==='paused'&&state.dialogResume);showDialog('<div class="dialog-icon">🪄</div><h2>小小冒险家，欢迎！</h2><div class="help-step"><b>1</b><span>选一座小岛，点击「开始冒险」。<br>初次玩，可以从萌芽小岛开始。</span></div><div class="help-step"><b>2</b><span>看泡泡里的字母，敲键盘上对应的键。<br>也可以点屏幕键盘；单词要依次敲哦。</span></div><div class="help-step"><b>3</b><span>收集 8 颗星星，带新伙伴回家！<br>按错没关系，星星会等你。</span></div><p>小提示：请切换为英文输入。<br>按 Esc 可以暂停，也可以关闭小窗口。</p>',resume);}
function resetReady(){clearInterval(state.clock);clearTimeout(state.nextTimer);state.session++;state.status='ready';state.hits=0;state.combo=0;state.target='';state.typed=0;state.seconds=60;$('#welcome').classList.remove('is-hidden');$('#bubbleField').innerHTML='<div class="preview-bubble bubble-one">'+(state.world===1?'C':'A')+'<span>✧</span></div><div class="preview-bubble bubble-two">S</div><div class="preview-bubble bubble-three">D</div>';$('#feedback').classList.remove('visible');$('#companionSpeech').textContent='你好呀，一起去找星星吧！';$('#keyboardHint').textContent='找到发光的按键，轻轻敲一下';$('#stageTip').textContent=state.mode==='relax'?'慢慢来，每一步都算数':'60 秒的小挑战，找齐 8 颗星星';update();}
document.querySelectorAll('[data-world]').forEach(button=>button.addEventListener('click',()=>{const value=Number(button.dataset.world);if(value===state.world)return;state.world=value;document.querySelectorAll('[data-world]').forEach(b=>b.classList.toggle('selected',b===button));$('#locationName').textContent=worlds[value].name;$('#locationEmoji').textContent=worlds[value].emoji;$('#sceneArt').style.filter=worlds[value].filter;$('#rewardName').textContent=worlds[value].reward;resetReady();}));
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{if(state.mode===button.dataset.mode)return;state.mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});resetReady();}));
$('#startButton').onclick=start;$('#pauseButton').onclick=pause;$('#soundButton').onclick=()=>{state.sound=!state.sound;updateSound();sound();};$('#collectionNav').onclick=showCollection;$('#helpButton').onclick=showHelp;$('#howtoButton').onclick=showHelp;$('#adventureNav').onclick=()=>{if($('#gameDialog').open)closeDialog(true);$('#stage').scrollIntoView({behavior:'smooth',block:'center'});};$('#closeDialog').onclick=()=>closeDialog(true);$('#gameDialog').addEventListener('cancel',event=>{event.preventDefault();closeDialog(true);});
document.addEventListener('keydown',event=>{if(event.ctrlKey||event.metaKey||event.altKey||event.repeat||event.isComposing||$('#gameDialog').open)return;if(['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName))return;if(event.key==='Escape'){if(state.status==='playing'){event.preventDefault();pause();}return;}if(event.key==='Enter'&&['ready','finished'].includes(state.status)){if(event.target.tagName!=='BUTTON'){event.preventDefault();start();}return;}if(/^[a-zA-Z]$/.test(event.key)){event.preventDefault();type(event.key.toLowerCase());}if(event.key==='Backspace'&&state.status==='playing'){event.preventDefault();if(state.typed>0){state.typed--;drawTarget();update();}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.status==='playing')pause();});
update();
