(function(root){
  const KEY='gulu-custom-library-v1';
  function code(text,kind){const clean=String(text||'').replace(/[’‘]/g,"'").replace(/[–—]/g,'-').trim();return (kind==='sentence'?clean.replace(/[.,!?;:]/g,' '):clean).replace(/\s+/g,' ').toUpperCase();}
  function entry(input,kind){const text=String(input.text||'').trim(),word=code(text,kind);if(text.length>500||!word||word.length>300||!/[A-Z]/.test(word)||!/^[A-Z .'-]+$/.test(word))throw Error('英文须为字母、空格或英文标点（数字请改为英文），每条不超过300字符：'+text.slice(0,30));return {text,word,meaning:String(input.meaning||'').trim().slice(0,500),ipa:String(input.ipa||'').trim().slice(0,150),note:String(input.note||'').slice(0,300),source:String(input.source||'manual').slice(0,40)};}
  function validate(group){try{return !!group&&typeof group.id==='string'&&group.id.length<=100&&typeof group.name==='string'&&group.name.length>0&&group.name.length<=50&&['word','sentence'].includes(group.kind)&&Array.isArray(group.entries)&&group.entries.length>0&&group.entries.length<=300&&group.entries.every(e=>typeof e.text==='string'&&typeof e.meaning==='string'&&typeof e.ipa==='string'&&entry(e,group.kind).word===e.word)&&new Set(group.entries.map(e=>e.word)).size===group.entries.length;}catch{return false;}}
  function parse(text,kind){return String(text).split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map((line,i)=>{
    line=line.replace(/^\d+[.)、]\s*/,'');let parts=line.split(/\t|\s*\|\s*/);
    if(parts.length===1){const at=line.search(/[\u3400-\u9fff]/);parts=at>0?[line.slice(0,at).trim(),line.slice(at)]:[line];}
    let english=parts[0],ipa=parts[2]||'';const match=english.match(/\s+\/([^/]+)\/\s*$/);if(match){ipa=ipa||match[1];english=english.slice(0,match.index);}
    try{return entry({text:english,meaning:parts[1]||'',ipa},kind);}catch(e){throw Error('第'+(i+1)+'行：'+e.message);}
  });}
  function enrich(entries,kind,vocabulary){const lookup=new Map((vocabulary?.entries||[]).map(e=>[e.word,e]));if(kind==='sentence'){lookup.clear();for(const tier of root.GuluDialogues?.tiers||[])for(const record of tier)for(let n=1;n<=3;n++){const lines=record.lines.slice(0,n);lookup.set(code(lines.map(l=>l.text).join(' '),'sentence'),{meaning:lines.map(l=>l.meaning).join(' / '),ipa:''});}}return entries.map(e=>{const found=lookup.get(e.word);return found?{...e,meaning:e.meaning||found.meaning,ipa:e.ipa||found.ipa,source:(!e.meaning||!e.ipa)?'local':e.source}:e;});}
  function repository(storage){function list(){const raw=storage.getItem(KEY);if(!raw)return [];const items=JSON.parse(raw);if(!Array.isArray(items)||items.some(g=>!validate(g)))throw Error('自定义词库数据异常，原记录未覆盖。');return items;}
    return {list,save(group){const rows=[];const seen=new Set();for(const e of group.entries){const item=entry(e,group.kind);if(!seen.has(item.word)){rows.push(item);seen.add(item.word);}}const clean={id:group.id||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),name:String(group.name||'').trim(),kind:group.kind,entries:rows};if(!validate(clean))throw Error('请填写分组名称，并加入1至300条有效内容。');const all=list(),i=all.findIndex(g=>g.id===clean.id);if(i>=0)all[i]=clean;else{if(all.length>=30)throw Error('最多保存30个分组。');all.push(clean);}storage.setItem(KEY,JSON.stringify(all));return clean;},remove(id){storage.setItem(KEY,JSON.stringify(list().filter(g=>g.id!==id)));},importGroups(groups){if(!Array.isArray(groups)||groups.some(g=>!validate(g)))throw Error('分组文件无效');const all=list();if(all.length+groups.length>30)throw Error('导入后超过30组');const added=groups.map((g,i)=>({...g,id:Date.now().toString(36)+'-'+i+'-'+Math.random().toString(36).slice(2)}));storage.setItem(KEY,JSON.stringify([...all,...added]));}};}
  root.GuluCustomLibrary={code,entry,validate,parse,enrich,repository};if(typeof module!=='undefined'&&module.exports)module.exports=root.GuluCustomLibrary;
})(typeof globalThis!=='undefined'?globalThis:this);
