const {test}=require('node:test'),assert=require('node:assert/strict');
const {GardenGame,SKILLS}=require('../engine.js'),save=require('../save.js');
function setup(kind){const g=new GardenGame({random:()=>.4});g.start();g.enemies=[];g.spawnIn=100;g.fireStrength=0;Object.assign(g.skills[0],SKILLS[kind],{kind});return g;}
function spawn(g,x=600,y=280,type='walker',hp=10000){const z=g.spawn(x,y,type,false);z.hp=z.maxHp=hp;return z;}
function tick(g,t){for(let i=0;i<t*60;i++)g.update(1/60);}
test('new skills have four-character names and lightning hits ten different enemies with rising damage',()=>{for(const kind of ['charm','rage','lightning','blackhole','clones','deathchain','judgment'])assert.equal(SKILLS[kind].name.length,4);const g=setup('lightning');const zs=Array.from({length:12},(_,i)=>spawn(g,300+i*55));g.cast(0);assert.equal(zs.filter(z=>z.hp<z.maxHp).length,10);assert.ok(zs[8].maxHp-zs[8].hp>zs[0].maxHp-zs[0].hp);});
test('charm ignores the aim point and converts one frontline hostile per lane',()=>{const g=setup('charm');g.auto=true;const lane0=spawn(g,200,140,'boss'),rear0=spawn(g,800,140),lane3=spawn(g,400,365),rear3=spawn(g,820,365);g.setAim(810,400);g.cast(0);assert.ok(lane0.charmed&&lane3.charmed);assert.ok(!rear0.charmed&&!rear3.charmed);const effect=g.effects.find(e=>e.kind==='charm');assert.deepEqual(effect.targets,[{x:lane0.x,y:lane0.y},{x:lane3.x,y:lane3.y}]);const snapshot=save.encode(g);assert.ok(save.validate(snapshot));const loaded=new GardenGame();assert.ok(save.restore(loaded,snapshot));assert.ok(loaded.enemies.find(z=>z.boss).charmed);});
test('black hole uses the reduced 105px radius, pulls and damages hostiles, finishes with a blast and preserves allies',()=>{const g=setup('blackhole');const a=spawn(g,600),b=spawn(g,680),friend=spawn(g,620,100);friend.charmed=true;g.cast(0);const effect=g.effects.find(e=>e.kind==='blackhole');assert.equal(effect?.radius,105);tick(g,1);assert.ok(a.hp<10000&&b.hp<10000);assert.equal(friend.hp,10000);g.enemies=g.enemies.filter(z=>z!==friend);const hp=a.hp;tick(g,2.2);assert.ok(a.hp<hp);assert.ok(!g.effects.some(e=>e.kind==='blackhole'));});
test('clones fire independently while normal shooting is off and inherit multishot and damage',()=>{const g=setup('clones');spawn(g,1000);g.stacks.multishot=2;g.stacks.power=2;g.cast(0);g.update(1/60);assert.equal(g.bullets.length,6);assert.ok(g.bullets.every(b=>b.damage===36));g.pause();const duration=g.clones;tick(g,1);assert.equal(g.clones,duration);g.resume();tick(g,8.1);assert.equal(g.clones,0);});
test('death chain propagates each kill once without hurting allies or recurring after expiration',()=>{const g=setup('deathchain');const a=spawn(g,400,280,'walker',100),b=spawn(g,550,280,'walker',100),c=spawn(g,700,280,'walker',100),friend=spawn(g,450,280,'walker',100);friend.charmed=true;g.cast(0);g.damage(a,101);assert.ok(b.hp<=0&&c.hp<=0);assert.equal(g.kills,3);assert.equal(g.score,30);assert.equal(friend.hp,100);assert.equal(g.deathQueue.length,0);const z=spawn(g,900,100);g.cast(0);tick(g,8.2);assert.equal(z.deathMark,0);});
test('judgment automatically executes the six healthiest enemies and supports target upgrades',()=>{let g=setup('judgment');const zs=Array.from({length:8},(_,i)=>spawn(g,300+i*55,280,'walker',1000+i*100));g.cast(0);assert.equal(zs.filter(z=>z.hp<=0).length,6);g=setup('judgment');g.stacks.judgmentTargets=2;const boss=spawn(g,900,280,'boss',10000);const others=Array.from({length:7},(_,i)=>spawn(g,400+i*40,280,'walker',1000));g.cast(0);assert.equal(others.filter(z=>z.hp<=0).length,7);assert.equal(boss.hp,4500);});
test('all persistent new skill states round-trip through saves and legacy snapshots still load',()=>{for(const kind of ['lightning','blackhole','clones','deathchain','judgment']){const g=setup(kind);spawn(g);g.cast(0);const snapshot=save.encode(g);assert.ok(save.validate(snapshot),kind);const loaded=new GardenGame();assert.ok(save.restore(loaded,snapshot));assert.equal(loaded.skills[0].kind,kind);loaded.resume();loaded.update(.02);}const g=setup('clones');const snapshot=save.encode(g);delete snapshot.state.clones;delete snapshot.state.cloneShot;assert.ok(save.restore(g,snapshot));assert.equal(g.clones,0);});
test('each clone matches ordinary captain cadence without a skill speed bonus',()=>{
 for(const strength of [.1,.3,1])for(const rapid of [0,3]){
  const g=setup('clones');spawn(g,1000);g.fireStrength=strength;g.stacks.rapid=rapid;g.auto=true;
  const counts={captain:0,upper:0,lower:0};g.shoot=origin=>{counts[!origin?'captain':origin.y<g.hero.y?'upper':'lower']++;};
  g.cast(0);tick(g,2);assert.equal(counts.upper,counts.captain);assert.equal(counts.lower,counts.captain);
 }
});
test('clones keep ordinary cadence during rage and use default cadence when normal fire is off',()=>{
 const g=setup('clones');spawn(g,1000);g.cast(0);assert.equal(g.ordinaryShotInterval,.5);g.rage=5;
 const counts={captain:0,clone:0};g.shoot=origin=>{counts[origin?'clone':'captain']++;};tick(g,2);
 assert.ok(counts.captain>counts.clone/2);assert.ok(counts.clone/2<=4);
});
