const {test}=require('node:test'),assert=require('node:assert/strict');
const {GardenGame,CARDS,SKILLS}=require('../engine.js'),save=require('../save.js');
function game(){const g=new GardenGame({random:()=>.4});g.start();g.enemies=[];g.spawnIn=100;g.fireStrength=0;return g;}
function equip(g,kind,slot){g.status='upgrade';g.offers=[CARDS.find(c=>c.skill===kind)];assert.ok(g.chooseCard('skill-'+kind,slot));g.spawnIn=100;}
function tick(g,seconds){for(let i=0;i<Math.round(seconds*60);i++)g.update(1/60);}
test('new skill cards require a slot, preserve three slots and reset on a new run',()=>{const g=game();g.status='upgrade';g.offers=[CARDS.find(card=>card.id==='skill-charm')];assert.equal(g.chooseCard('skill-charm'),false);assert.equal(g.chooseCard('skill-charm',3),false);assert.ok(g.chooseCard('skill-charm',1));assert.equal(g.skills[1].kind,'charm');assert.equal(g.skills[1].duration,13);assert.equal(g.skills.length,3);g.start();assert.deepEqual(g.skills.map(s=>s.kind),['laser','freeze','melon']);});
test('skill cards are rare beside attribute cards and no offer contains two skills',()=>{let seed=17;const g=new GardenGame({random:()=>{seed=(seed*1103515245+12345)>>>0;return seed/2**32;}});g.start();let skills=0,attributes=0;for(let i=0;i<200;i++){g.status='playing';g.offerCards();const offered=g.offers.filter(card=>card.skill);assert.ok(offered.length<=1);skills+=offered.length;attributes+=3-offered.length;}assert.ok(skills<attributes/10);});
test('charm converts the foremost hostile in every lane, includes bosses, deals no damage and turns them right',()=>{const g=game();equip(g,'charm',2);const boss=g.spawn(500,140,'boss',false),rear0=g.spawn(700,140,'walker',false),front1=g.spawn(450,215,'walker',false),rear1=g.spawn(800,215,'walker',false),front2=g.spawn(520,290,'walker',false),front3=g.spawn(480,365,'walker',false),front4=g.spawn(510,430,'walker',false);g.setAim(900,290);g.cast(2);for(const z of [boss,front1,front2,front3,front4])assert.equal(z.charmed,true);for(const z of [rear0,rear1])assert.equal(z.charmed,undefined);assert.equal(boss.hp,boss.maxHp);const x=boss.x;tick(g,1);assert.ok(boss.x>x);assert.equal(g.health,8);});
test('charmed zombies fight enemies, do not take friendly fire, and dying gives no kill score',()=>{const g=game();const ally=g.spawn(500,280,'walker',false),foe=g.spawn(555,280,'walker',false);ally.charmed=true;g.damage(ally,1000,'laser');assert.equal(ally.hp,ally.maxHp);tick(g,.7);assert.ok(ally.hp<ally.maxHp);assert.ok(foe.hp<foe.maxHp);const score=g.score;g.damage(ally,10000,'zombieBite');assert.equal(g.score,score);assert.equal(g.kills,0);});
test('charmed zombies leave the screen and do not block wave completion',()=>{const g=game();const ally=g.spawn(1099,280,'walker',false);ally.charmed=true;tick(g,.2);assert.equal(g.enemies.length,0);const another=g.spawn(600,280,'walker',false);another.charmed=true;g.spawned=g.quota;g.update(.02);assert.equal(g.status,'upgrade');});
test('rage lasts 5 seconds, shoots ten stronger bullets with fire disabled and pauses correctly',()=>{const g=game();equip(g,'rage',0);g.spawn(1000,280,'walker',false);g.cast(0);assert.equal(g.rage,5);g.shoot();assert.equal(g.bullets.length,10);assert.ok(g.bullets.every(b=>b.damage===72));g.bullets=[];tick(g,.3);assert.ok(g.bullets.length>=20);g.pause();tick(g,1);assert.ok(g.rage>4.6);g.resume();tick(g,5);assert.equal(g.rage,0);g.bullets=[];tick(g,.5);assert.equal(g.bullets.length,0);g.stacks.rageDuration=3;g.cast(0);assert.equal(g.rage,8);});
test('save restores loadout, allies and rage, and rejects invalid skill IDs',()=>{const g=game();equip(g,'charm',0);equip(g,'rage',1);g.spawn(800,280,'walker',false);g.enemies[0].charmed=true;g.cast(1);const data=save.encode(g);assert.ok(save.validate(data));const loaded=new GardenGame();assert.ok(save.restore(loaded,data));assert.deepEqual(loaded.skills.map(s=>s.kind),['charm','rage','melon']);assert.equal(loaded.rage,5);assert.ok(loaded.enemies[0].charmed);data.state.skills[0].kind='bad';assert.equal(save.validate(data),false);});
test('rage doubles default cadence without changing per-volley damage',()=>{
 const g=game();equip(g,'rage',0);g.spawn(1000,280,'boss',false);g.cast(0);let volleys=0;const shoot=g.shoot.bind(g);g.shoot=origin=>{if(!origin)volleys++;shoot(origin);};tick(g,1);assert.equal(volleys,4);assert.ok(g.bullets.every(b=>b.damage===72));
});

test('rage bullets are cleared at expiry so the last volley cannot linger and spike collision work',()=>{const g=game();equip(g,'rage',0);g.spawn(1000,280,'walker',false);g.cast(0);g.update(.19);assert.ok(g.bullets.length>0&&g.bullets.every(b=>b.rageShot));g.update(.02);g.rage=.01;g.update(.02);assert.ok(g.bullets.every(b=>!b.rageShot));});

test('rage expiry removes queued burst bullets in one update without changing normal bullets',()=>{const g=game();equip(g,'rage',0);g.spawn(1000,280,'walker',false);g.cast(0);g.bullets.push({x:300,y:100,px:300,py:100,vx:0,vy:0,life:2.5,damage:1,rageShot:false,pierce:0,bounces:0,hitIds:new Set()});g.rage=.001;g.update(.02);assert.equal(g.bullets.filter(b=>b.rageShot).length,0);assert.equal(g.bullets.filter(b=>!b.rageShot).length,1);});

test('rage doubles normal cadence until its 0.12-second safety cap',()=>{const g=game();for(const strength of [.1,.3,.7])for(const rapid of [0,2]){g.fireStrength=strength;g.stacks.rapid=rapid;assert.equal(g.rageShotInterval,Math.max(.12,g.ordinaryShotInterval/2));}g.fireStrength=1;g.stacks.rapid=8;assert.equal(g.ordinaryShotInterval/2<.12,true);assert.equal(g.rageShotInterval,.12);g.fireStrength=0;g.stacks.rapid=0;assert.equal(g.rageShotInterval,.25);});
