const {test}=require('node:test'),assert=require('node:assert/strict');const {GardenGame,SKILLS}=require('../engine.js'),save=require('../save.js');
function setup(kind){const g=new GardenGame({random:()=>.4});g.start();g.enemies=[];g.spawnIn=100;Object.assign(g.skills[0],SKILLS[kind],{kind});return g;}
test('area skills use a click-pinned center, except charm which selects every lane frontline',()=>{for(const kind of ['melon','blackhole']){const g=setup(kind);g.auto=true;g.spawn(800,300,'walker',false);assert.equal(g.skillAuto,true);assert.equal(g.skillTarget(kind).x,800);g.setSkillAim(300,150);g.setAim(950,450);assert.deepEqual(g.skillTarget(kind),{x:300,y:150});g.cast(0);const effect=g.effects.find(e=>e.kind===kind);assert.equal(effect.x,300);assert.equal(effect.y,150);g.skillAuto=true;assert.equal(g.skillTarget(kind).x,800);}const charm=setup('charm');const front=charm.spawn(400,140,'walker',false),rear=charm.spawn(800,140,'walker',false);charm.setSkillAim(900,400);charm.cast(0);assert.ok(front.charmed);assert.ok(!rear.charmed);});
test('manual judgment starts from the clicked location and hits up to six nearby targets',()=>{const g=setup('judgment'),a=g.spawn(300,180,'walker',false),b=g.spawn(850,400,'boss',false);for(let i=0;i<6;i++)g.spawn(320+i*8,180,'walker',false);g.setSkillAim(310,180);g.cast(0);assert.ok(a.hp<=0);assert.equal(b.hp,b.maxHp);});
test('manual lightning begins near clicked location, then chains automatically',()=>{const g=setup('lightning');g.spawn(300,180,'walker',false);g.spawn(850,400,'walker',false);g.setSkillAim(850,400);g.cast(0);assert.equal(g.effects.find(e=>e.kind==='lightning').points[0].x,850);});
test('manual aim survives saves, legacy snapshots default to automatic',()=>{const g=setup('charm');g.spawn(900,280,'walker',false);g.setSkillAim(350,200);const data=save.encode(g),loaded=new GardenGame();assert.ok(save.restore(loaded,data));assert.equal(loaded.skillAuto,false);assert.deepEqual(loaded.skillAim,{x:350,y:200});delete data.state.skillAim;delete data.state.skillAuto;assert.ok(save.restore(loaded,data));assert.equal(loaded.skillAuto,true);});
test('automatic aim resumes after five active seconds and tracks moving targets',()=>{const g=setup('charm');g.auto=true;g.spawnIn=100;g.spawn(850,300,'boss',false);g.setSkillAim(300,150);for(let i=0;i<299;i++)g.update(1/60);assert.equal(g.skillAuto,false);g.update(1/60);assert.equal(g.skillAuto,true);assert.equal(g.skillAimLeft,0);assert.deepEqual(g.skillTarget('charm'),g.target());g.enemies[0].x=500;assert.equal(g.skillTarget('charm').x,500);});
test('click expires even with ordinary auto shooting disabled; a new click restarts the window',()=>{const g=setup('charm');g.spawnIn=100;g.setSkillAim(300,150);for(let i=0;i<400;i++)g.update(1/60);assert.equal(g.skillAuto,true);g.auto=true;g.setSkillAim(350,160);for(let i=0;i<120;i++)g.update(1/60);g.setSkillAim(400,170);assert.equal(g.skillAimLeft,5);g.pause();g.update(.05);assert.equal(g.skillAimLeft,5);const snapshot=save.encode(g),loaded=new GardenGame();assert.ok(save.restore(loaded,snapshot));assert.equal(loaded.skillAimLeft,5);});

test('with ordinary auto fire disabled, expired skill points still select live enemies',()=>{const g=setup('charm');g.auto=false;g.spawn(850,300,'boss',false);g.setSkillAim(300,150);for(let i=0;i<300;i++)g.update(1/60);assert.equal(g.skillAuto,true);assert.equal(g.skillTarget('charm').x,Math.min(...g.enemies.filter(e=>e.hp>0&&!e.charmed).map(e=>e.x)));assert.notEqual(g.skillTarget('charm').x,300);});
